"""create ai_suggestion_usage_log

Revision ID: 8b1f2e4c9a7d
Revises: d4a2c8a0705b
Create Date: 2026-05-27 17:15:00.000000+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8b1f2e4c9a7d"
down_revision: Union[str, Sequence[str], None] = "d4a2c8a0705b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_suggestion_usage_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("bible_text_id", sa.Integer(), nullable=False),
        sa.Column("project_unit_id", sa.Integer(), nullable=False),
        sa.Column(
            "was_used", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "bible_text_id", name="uq_ai_usage_user_text"),
        schema="ai",
    )
    op.create_index(
        "idx_ai_usage_project_unit",
        "ai_suggestion_usage_log",
        ["project_unit_id"],
        unique=False,
        schema="ai",
    )
    op.create_index(
        "idx_ai_usage_user",
        "ai_suggestion_usage_log",
        ["user_id"],
        unique=False,
        schema="ai",
    )
    # ### end Alembic commands ###

    # --- Manual Permissions ---
    op.execute(
        "GRANT SELECT, INSERT, UPDATE ON ai.ai_suggestion_usage_log TO role_web_data"
    )
    op.execute(
        "GRANT USAGE, SELECT ON SEQUENCE ai.ai_suggestion_usage_log_id_seq TO role_web_data"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_ai_usage_user", table_name="ai_suggestion_usage_log", schema="ai"
    )
    op.drop_index(
        "idx_ai_usage_project_unit",
        table_name="ai_suggestion_usage_log",
        schema="ai",
    )
    op.drop_table("ai_suggestion_usage_log", schema="ai")
    # ### end Alembic commands ###
