"""create ai_suggestions schema

Revision ID: d4a2c8a0705b
Revises: 20260512_0900
Create Date: 2026-05-27 15:40:00.260749+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d4a2c8a0705b"
down_revision: Union[str, Sequence[str], None] = "20260512_0900"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_suggestion_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_unit_id", sa.Integer(), nullable=False),
        sa.Column("bible_id", sa.Integer(), nullable=False),
        sa.Column("book_code", sa.String(length=50), nullable=False),
        sa.Column("chapter_number", sa.Integer(), nullable=False),
        sa.Column("verse_start", sa.Integer(), nullable=False),
        sa.Column("verse_end", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default=sa.text("'queued'"),
            nullable=False,
        ),
        sa.Column(
            "retry_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_unit_id",
            "bible_id",
            "book_code",
            "chapter_number",
            "verse_start",
            "verse_end",
            name="uq_ai_jobs_range",
        ),
        schema="ai",
    )
    op.create_index(
        "idx_ai_suggestion_jobs_dedup",
        "ai_suggestion_jobs",
        ["project_unit_id", "bible_id", "book_code", "chapter_number"],
        unique=False,
        schema="ai",
    )
    op.create_index(
        "idx_ai_suggestion_jobs_status_created",
        "ai_suggestion_jobs",
        ["status", "created_at"],
        unique=False,
        schema="ai",
    )
    op.create_table(
        "ai_suggestions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bible_text_id", sa.Integer(), nullable=False),
        sa.Column("project_unit_id", sa.Integer(), nullable=False),
        sa.Column("suggested_text", sa.Text(), nullable=False),
        sa.Column("model_info", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "bible_text_id", "project_unit_id", name="uq_ai_suggestions_per_text_unit"
        ),
        schema="ai",
    )
    op.create_index(
        "idx_ai_suggestions_lookup",
        "ai_suggestions",
        ["project_unit_id", "bible_text_id"],
        unique=False,
        schema="ai",
    )
    # ### end Alembic commands ###

    # --- Manual Permissions ---
    op.execute("GRANT SELECT, INSERT ON ai.ai_suggestion_jobs TO role_web_data")
    op.execute(
        "GRANT USAGE, SELECT ON SEQUENCE ai.ai_suggestion_jobs_id_seq TO role_web_data"
    )
    op.execute("GRANT SELECT ON ai.ai_suggestions TO role_web_data")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_ai_suggestions_lookup", table_name="ai_suggestions", schema="ai")
    op.drop_table("ai_suggestions", schema="ai")
    op.drop_index(
        "idx_ai_suggestion_jobs_status_created",
        table_name="ai_suggestion_jobs",
        schema="ai",
    )
    op.drop_index(
        "idx_ai_suggestion_jobs_dedup", table_name="ai_suggestion_jobs", schema="ai"
    )
    op.drop_table("ai_suggestion_jobs", schema="ai")
    # ### end Alembic commands ###
